# Generated by Django 4.1.6 on 2023-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.BooleanField(null=True),
        ),
    ]
