# Generated by Django 4.1.6 on 2023-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_member_membership_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_end_date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.BooleanField(default='2000-01-01', null=True),
        ),
    ]
