# Generated by Django 4.1.6 on 2023-04-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_member_membership_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_start_date', models.DateField(default='2000-01-01', null=True)),
                ('membership_end_date', models.DateField(default='2000-01-01', null=True)),
                ('membership_status', models.BooleanField(default='2000-01-01', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_start_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_status',
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.membership'),
        ),
    ]
