# Generated by Django 4.1.6 on 2023-04-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_membership_remove_member_membership_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.member'),
        ),
    ]
